function ddtheta = getDDtheta(theta, dtheta, p, dp, t, P)
    L = P.L;
    R = P.R;
    m = P.m;
    M = P.M;
    g = P.g;
    k = P.k;
    F = P.F;
    mu = P.mu;
    p0 = P.p0;

    ddtheta = (-1) .* (4 .* L .^ 2 .* m .* M .* cos(theta) .^ 2 + 4 .* L .^ 2 .* ...
   M .^ 2 .* cos(theta) .^ 2 + 4 .* L .^ 4 .* m .* M .* mu .* R .* ( ...
  abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^  ...
  2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (-1 / 2) .* cos(theta) .^ 3 .* ...
   (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1) .* sign( ...
  dtheta) .* sin(theta) + 4 .* L .^ 2 .* m .* M .* sin(theta) .^ 2 + ...
   4 .* L .^ 2 .* M .^ 2 .* sin(theta) .^ 2 + 4 .* L .^ 4 .* m .* M  ...
  .* cos(theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) ...
   .^ (-1) .* sin(theta) .^ 2 + 4 .* L .^ 4 .* m .* M .* mu .* R .*  ...
  (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^  ...
  2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (-1 / 2) .* cos(theta) .* (R  ...
  .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1) .* sign(dtheta)  ...
  .* sin(theta) .^ 3) .^ (-1) .* ((-2) .* L .^ 2 .* M .* cos(theta)  ...
  .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .*  ...
  sin(theta) .* (2 .* (g .* M + k .* (p + (-1) .* p0)) + 2 .*  ...
  dtheta .^ 2 .* L .^ 2 .* M .* cos(theta) .^ 2 .* (R .^ 2 + (-1) .* ...
   L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) + 2 .* F(t) + (-2) .*  ...
  dtheta .^ 2 .* L .^ 4 .* M .* cos(theta) .^ 2 .* (R .^ 2 + (-1) .* ...
   L .^ 2 .* cos(theta) .^ 2) .^ (-3 / 2) .* sin(theta) .^ 2 + (-2)  ...
  .* dtheta .^ 2 .* L .^ 2 .* M .* (R .^ 2 + (-1) .* L .^ 2 .* cos( ...
  theta) .^ 2) .^ (-1 / 2) .* sin(theta) .^ 2) + 2 .* M .* (2 .*  ...
  dtheta .^ 2 .* L .^ 4 .* m .* mu .* R .* (abs(L .* cos(theta)) .^  ...
  2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^  ...
  2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta))  ...
  .^ 2) .^ (-1 / 2) .* cos(theta) .^ 4 .* (R .^ 2 + (-1) .* L .^ 2  ...
  .* cos(theta) .^ 2) .^ (-1) .* sign(dtheta) + 2 .* g .* L .^ 2 .*  ...
  m .* mu .* R .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta))  ...
  .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .*  ...
  cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (-1 / 2) .*  ...
  cos(theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (-1 / 2) .* sign(dtheta) + (-2) .* k .* L .^ 2 .* mu .* p .* R  ...
  .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L  ...
  .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) ...
   .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (-1 / 2) .* cos(theta) .^ 2  ...
  .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .*  ...
  sign(dtheta) + 2 .* k .* L .^ 2 .* mu .* p0 .* R .* (abs(L .* cos( ...
  theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (-1 / 2) .* cos(theta) .^ 2 .* (R .^ 2 +  ...
  (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sign(dtheta) +  ...
  4 .* dtheta .^ 2 .* L .^ 4 .* m .* cos(theta) .^ 3 .* (R .^ 2 + ( ...
  -1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1) .* sin(theta) + 2 .*  ...
  dtheta .^ 2 .* L .^ 4 .* M .* cos(theta) .^ 3 .* (R .^ 2 + (-1) .* ...
   L .^ 2 .* cos(theta) .^ 2) .^ (-1) .* sin(theta) + (-2) .*  ...
  dtheta .^ 2 .* L .^ 6 .* m .* mu .* R .* (abs(L .* cos(theta)) .^  ...
  2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^  ...
  2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta))  ...
  .^ 2) .^ (-1 / 2) .* cos(theta) .^ 4 .* (R .^ 2 + (-1) .* L .^ 2  ...
  .* cos(theta) .^ 2) .^ (-2) .* sign(dtheta) .* sin(theta) .^ 2 +  ...
  2 .* g .* L .^ 2 .* m .* mu .* R .* (abs(L .* cos(theta)) .^ 2 +  ...
  abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 +  ...
  (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^  ...
  2) .^ (-1 / 2) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^  ...
  (-1 / 2) .* sign(dtheta) .* sin(theta) .^ 2 + (-2) .* k .* L .^ 2  ...
  .* mu .* p .* R .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin( ...
  theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^  ...
  2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (-1 / 2) ...
   .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .*  ...
  sign(dtheta) .* sin(theta) .^ 2 + 2 .* k .* L .^ 2 .* mu .* p0 .*  ...
  R .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs( ...
  L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^  ...
  2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (-1 / 2) .* (R .^ 2 + (-1)  ...
  .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sign(dtheta) .* sin( ...
  theta) .^ 2 + (-4) .* dtheta .^ 2 .* L .^ 6 .* m .* cos(theta) .^  ...
  3 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-2) .* sin( ...
  theta) .^ 3 + (-2) .* dtheta .^ 2 .* L .^ 6 .* M .* cos(theta) .^  ...
  3 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-2) .* sin( ...
  theta) .^ 3 + (-4) .* dtheta .^ 2 .* L .^ 4 .* m .* cos(theta) .*  ...
  (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1) .* sin(theta) ...
   .^ 3 + (-2) .* dtheta .^ 2 .* L .^ 4 .* M .* cos(theta) .* (R .^  ...
  2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1) .* sin(theta) .^ 3  ...
  + (-2) .* dtheta .^ 2 .* L .^ 6 .* m .* mu .* R .* (abs(L .* cos( ...
  theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (-1 / 2) .* cos(theta) .^ 2 .* (R .^ 2 +  ...
  (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-2) .* sign(dtheta) .* sin( ...
  theta) .^ 4 + (-2) .* dtheta .^ 2 .* L .^ 4 .* m .* mu .* R .* ( ...
  abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^  ...
  2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (-1 / 2) .* (R .^ 2 + (-1) .*  ...
  L .^ 2 .* cos(theta) .^ 2) .^ (-1) .* sign(dtheta) .* sin(theta)  ...
  .^ 4 + 2 .* dtheta .* L .^ 2 .* M .* cos(theta) .^ 2 .* (R .^ 2 +  ...
  (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* (dp + dtheta .*  ...
  L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^  ...
  2) .^ (-1 / 2) .* sin(theta)) + (-2) .* dtheta .* L .^ 4 .* M .*  ...
  cos(theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (-3 / 2) .* sin(theta) .^ 2 .* (dp + dtheta .* L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) + (-2) .* dtheta .* L .^ 2 .* M .* (R .^ 2 + (-1)  ...
  .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta) .^ 2 .* ( ...
  dp + dtheta .* L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* ...
   cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) + 2 .* (g .* L .^ 2  ...
  .* m .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) ...
   .^ (-1 / 2) .* sin(theta) + g .* L .^ 2 .* M .* cos(theta) .* (R  ...
  .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin( ...
  theta)) + (-2) .* (M .* (dp + dtheta .* L .^ 2 .* cos(theta) .* ( ...
  R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin( ...
  theta)) .* (dtheta .* L .^ 2 .* cos(theta) .^ 2 .* (R .^ 2 + (-1)  ...
  .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) + (-1) .* dtheta .* L  ...
  .^ 4 .* cos(theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta)  ...
  .^ 2) .^ (-3 / 2) .* sin(theta) .^ 2 + (-1) .* dtheta .* L .^ 2 .* ...
   (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin( ...
  theta) .^ 2) + (1 / 2) .* m .* (2 .* dtheta .^ 2 .* L .^ 4 .* cos( ...
  theta) .^ 3 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ ( ...
  -1) .* sin(theta) + (-2) .* dtheta .^ 2 .* L .^ 6 .* cos(theta)  ...
  .^ 3 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-2) .*  ...
  sin(theta) .^ 3 + (-2) .* dtheta .^ 2 .* L .^ 4 .* cos(theta) .* ( ...
   R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1) .* sin(theta)  ...
 .^ 3))));
end