function ddp = getDDp(theta, dtheta, p, dp, t, P)
    L = P.L;
    R = P.R;
    m = P.m;
    M = P.M;
    g = P.g;
    k = P.k;
    F = P.F;
    mu = P.mu;
    p0 = P.p0;

    ddp = (-1) .* M .^ (-1) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (-1 / 2) .* ((-1) .* m .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2  ...
  + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2  ...
  + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta))  ...
  .^ 2) .^ (1 / 2) .* cos(theta) .^ 2 + (-1) .* M .* R .^ 2 .* (abs( ...
  L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .*  ...
  cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1  ...
  / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 2 + L .^ 2  ...
  .* m .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 +  ...
  abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) ...
   .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta)  ...
  .^ 4 + L .^ 2 .* M .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin( ...
  theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^  ...
  2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2)  ...
  .* cos(theta) .^ 4 + (-1) .* L .^ 2 .* m .* mu .* R .* cos(theta)  ...
  .^ 3 .* sign(dtheta) .* sin(theta) + (-1) .* m .* R .^ 2 .* (abs( ...
  L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .*  ...
  cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1  ...
  / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* sin(theta) .^ 2 + (-1) .*  ...
  M .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta))  ...
  .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .*  ...
  cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .*  ...
  sin(theta) .^ 2 + L .^ 2 .* M .* (abs(L .* cos(theta)) .^ 2 + abs( ...
  L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) ...
   .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2)  ...
  .^ (1 / 2) .* cos(theta) .^ 2 .* sin(theta) .^ 2 + (-1) .* L .^ 2  ...
  .* m .* mu .* R .* cos(theta) .* sign(dtheta) .* sin(theta) .^ 3)  ...
  .^ (-1) .* ((-1) .* dtheta .^ 2 .* L .^ 2 .* m .* M .* R .^ 2 .* ( ...
  abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^  ...
  2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 4 + ( ...
  -1) .* dtheta .^ 2 .* L .^ 2 .* M .^ 2 .* R .^ 2 .* (abs(L .* cos( ...
  theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 4 + dtheta .^ 2  ...
  .* L .^ 4 .* m .* M .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin( ...
  theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^  ...
  2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2)  ...
  .* cos(theta) .^ 6 + dtheta .^ 2 .* L .^ 4 .* M .^ 2 .* (abs(L .*  ...
  cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 6 + (-1) .* g .* ...
   m .* M .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin( ...
  theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^  ...
  2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2)  ...
  .* cos(theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) ...
   .^ (1 / 2) + (-1) .* g .* M .^ 2 .* R .^ 2 .* (abs(L .* cos( ...
  theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 2 .* (R .^ 2 + ( ...
  -1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) + (-1) .* k .* m .*  ...
  p .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta))  ...
  .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .*  ...
  cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .*  ...
  cos(theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (1 / 2) + (-1) .* k .* M .* p .* R .^ 2 .* (abs(L .* cos(theta) ...
  ) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* ( ...
  R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin( ...
  theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 2 .* (R .^ 2 + (-1) .*  ...
  L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) + k .* m .* p0 .* R .^ 2 .*  ...
  (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^  ...
  2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 2 .*  ...
  (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) + k .* M  ...
  .* p0 .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin( ...
  theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^  ...
  2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2)  ...
  .* cos(theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) ...
   .^ (1 / 2) + g .* L .^ 2 .* m .* M .* (abs(L .* cos(theta)) .^ 2  ...
  + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2  ...
  + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta))  ...
  .^ 2) .^ (1 / 2) .* cos(theta) .^ 4 .* (R .^ 2 + (-1) .* L .^ 2 .* ...
   cos(theta) .^ 2) .^ (1 / 2) + g .* L .^ 2 .* M .^ 2 .* (abs(L .*  ...
  cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 4 .* (R .^ 2 + ( ...
  -1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) + k .* L .^ 2 .* m .* ...
   p .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 +  ...
  abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) ...
   .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta)  ...
  .^ 4 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) +  ...
  k .* L .^ 2 .* M .* p .* (abs(L .* cos(theta)) .^ 2 + abs(L .*  ...
  sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .*  ...
  L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1  ...
  / 2) .* cos(theta) .^ 4 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta)  ...
  .^ 2) .^ (1 / 2) + (-1) .* k .* L .^ 2 .* m .* p0 .* (abs(L .*  ...
  cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 4 .* (R .^ 2 + ( ...
  -1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) + (-1) .* k .* L .^  ...
  2 .* M .* p0 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta))  ...
  .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .*  ...
  cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .*  ...
  cos(theta) .^ 4 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (1 / 2) + (-1) .* m .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 +  ...
  abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 +  ...
  (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^  ...
  2) .^ (1 / 2) .* cos(theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .*  ...
  cos(theta) .^ 2) .^ (1 / 2) .* F(t) + (-1) .* M .* R .^ 2 .* (abs( ...
  L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .*  ...
  cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1  ...
  / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 2 .* (R .^  ...
  2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) .* F(t) + L .^  ...
  2 .* m .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + ...
   abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos( ...
  theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* cos( ...
  theta) .^ 4 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1  ...
  / 2) .* F(t) + L .^ 2 .* M .* (abs(L .* cos(theta)) .^ 2 + abs(L  ...
  .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1)  ...
  .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^  ...
  (1 / 2) .* cos(theta) .^ 4 .* (R .^ 2 + (-1) .* L .^ 2 .* cos( ...
  theta) .^ 2) .^ (1 / 2) .* F(t) + (-1) .* k .* L .^ 2 .* m .* mu  ...
  .* p .* R .* cos(theta) .^ 3 .* (R .^ 2 + (-1) .* L .^ 2 .* cos( ...
  theta) .^ 2) .^ (1 / 2) .* sign(dtheta) .* sin(theta) + (-1) .* k  ...
  .* L .^ 2 .* M .* mu .* p .* R .* cos(theta) .^ 3 .* (R .^ 2 + ( ...
  -1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) .* sign(dtheta) .*  ...
  sin(theta) + k .* L .^ 2 .* m .* mu .* p0 .* R .* cos(theta) .^ 3  ...
  .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) .*  ...
  sign(dtheta) .* sin(theta) + k .* L .^ 2 .* M .* mu .* p0 .* R .*  ...
  cos(theta) .^ 3 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (1 / 2) .* sign(dtheta) .* sin(theta) + (-1) .* L .^ 2 .* m .*  ...
  mu .* R .* cos(theta) .^ 3 .* (R .^ 2 + (-1) .* L .^ 2 .* cos( ...
  theta) .^ 2) .^ (1 / 2) .* F(t) .* sign(dtheta) .* sin(theta) +  ...
  dtheta .^ 2 .* L .^ 4 .* m .* M .* (abs(L .* cos(theta)) .^ 2 +  ...
  abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 +  ...
  (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^  ...
  2) .^ (1 / 2) .* cos(theta) .^ 4 .* sin(theta) .^ 2 + dtheta .^ 2  ...
  .* L .^ 4 .* M .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin( ...
  theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^  ...
  2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2)  ...
  .* cos(theta) .^ 4 .* sin(theta) .^ 2 + (-1) .* g .* m .* M .* R  ...
  .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 +  ...
  abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) ...
   .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* (R .^ 2 + ( ...
  -1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) .* sin(theta) .^ 2 +  ...
  (-1) .* g .* M .^ 2 .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs( ...
  L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) ...
   .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2)  ...
  .^ (1 / 2) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1  ...
  / 2) .* sin(theta) .^ 2 + (-1) .* k .* m .* p .* R .^ 2 .* (abs(L  ...
  .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .*  ...
  cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1  ...
  / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* (R .^ 2 + (-1) .* L .^ 2  ...
  .* cos(theta) .^ 2) .^ (1 / 2) .* sin(theta) .^ 2 + (-1) .* k .*  ...
  M .* p .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin( ...
  theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^  ...
  2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2)  ...
  .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) .* sin( ...
  theta) .^ 2 + k .* m .* p0 .* R .^ 2 .* (abs(L .* cos(theta)) .^  ...
  2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^  ...
  2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta))  ...
  .^ 2) .^ (1 / 2) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2)  ...
  .^ (1 / 2) .* sin(theta) .^ 2 + k .* M .* p0 .* R .^ 2 .* (abs(L  ...
  .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .*  ...
  cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1  ...
  / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* (R .^ 2 + (-1) .* L .^ 2  ...
  .* cos(theta) .^ 2) .^ (1 / 2) .* sin(theta) .^ 2 + g .* L .^ 2 .* ...
   m .* M .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin(theta)) .^ 2  ...
  + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos( ...
  theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2) .* cos( ...
  theta) .^ 2 .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1  ...
  / 2) .* sin(theta) .^ 2 + g .* L .^ 2 .* M .^ 2 .* (abs(L .* cos( ...
  theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (1 / 2) .* cos(theta) .^ 2 .* (R .^ 2 + ( ...
  -1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) .* sin(theta) .^ 2 +  ...
  (-1) .* m .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs(L .* sin( ...
  theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) .* L .^  ...
  2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2) .^ (1 / 2)  ...
  .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) .* F(t) ...
   .* sin(theta) .^ 2 + (-1) .* M .* R .^ 2 .* (abs(L .* cos(theta)) ...
   .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* ( ...
  R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin( ...
  theta)) .^ 2) .^ (1 / 2) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) ...
   .^ 2) .^ (1 / 2) .* F(t) .* sin(theta) .^ 2 + (-1) .* k .* L .^  ...
  2 .* m .* mu .* p .* R .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2  ...
  .* cos(theta) .^ 2) .^ (1 / 2) .* sign(dtheta) .* sin(theta) .^ 3  ...
  + (-1) .* k .* L .^ 2 .* M .* mu .* p .* R .* cos(theta) .* (R .^  ...
  2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2) .* sign(dtheta)  ...
  .* sin(theta) .^ 3 + k .* L .^ 2 .* m .* mu .* p0 .* R .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (1 / 2)  ...
  .* sign(dtheta) .* sin(theta) .^ 3 + k .* L .^ 2 .* M .* mu .* p0  ...
  .* R .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) ...
   .^ (1 / 2) .* sign(dtheta) .* sin(theta) .^ 3 + (-1) .* L .^ 2 .* ...
   m .* mu .* R .* cos(theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos( ...
  theta) .^ 2) .^ (1 / 2) .* F(t) .* sign(dtheta) .* sin(theta) .^  ...
  3 + dtheta .^ 2 .* L .^ 2 .* m .* M .* R .^ 2 .* (abs(L .* cos( ...
  theta)) .^ 2 + abs(L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos( ...
  theta) .* (R .^ 2 + (-1) .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) ...
   .* sin(theta)) .^ 2) .^ (1 / 2) .* sin(theta) .^ 4 + dtheta .^ 2  ...
  .* L .^ 2 .* M .^ 2 .* R .^ 2 .* (abs(L .* cos(theta)) .^ 2 + abs( ...
  L .* sin(theta)) .^ 2 + abs(L .^ 2 .* cos(theta) .* (R .^ 2 + (-1) ...
   .* L .^ 2 .* cos(theta) .^ 2) .^ (-1 / 2) .* sin(theta)) .^ 2)  ...
  .^ (1 / 2) .* sin(theta) .^ 4);
end